title: Cielo E-Commerce Java Client
description: Remote integration with Cielo E-Commerce API 3.0.
google_analytics: 
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
